runtime: python311

env_variables:
  PORT: 5000

entrypoint: python3 server.py

automatic_scaling:
  min_instances: 1
  max_instances: 10

health_check:
  path: /health
  port: 5000
  check_interval_sec: 10
  timeout_sec: 4